### ISSUE TITLE
Kod deneme bölümü çalışmıyor.

### ISSUE THREAD

**Issue by kahredici** [golang-tr/tour#2]
İngilizcesinde sıkıntı yok ancak Türkçesinde "Sunucu bekleniyor..." ve sonuç ekrana gelmiyor. Sanırım 2 gün öncesine kadar sıkıntı yoktu.

**Comment by roktas** [comment]
Raporladığınız için teşekkürler.  Bir güncelleme yapmamız lazım.  An itibarıyla çevirilerde kritik olan `content` dizininde son değişiklikten bugüne neler olmuş?

```sh
$ git log --oneline --since 2014-09-29 -- content | wc -l
80
```

Toplam 80 değişiklik, epey hallice!  Önce bunları bir güncelleyelim, sonrasında servisi tekrar ayağa kaldırırız.

**Comment by roktas** [comment]
Same issue: golang/go#15693 (the mentioned workaround has been applied).

**Comment by adg** [comment]
So you updated the tools repo before re-deploying? And it didn't work?

**Comment by roktas** [comment]
Yep ( "`go get -u golang.org/x/tools/playground && goapp serve deploy .`")

**Comment by adg** [comment]
Do you mean `goapp serve` or `goapp deploy` ? The former will not work, the latter will.

**Comment by roktas** [comment]
Sorry, there is a typo in my message.  I mean the latter `goapp deploy`.   Deployment seems successful.

**Comment by adg** [comment]
Can you show me the output of `cd $GOPATH/src/golang.org/x/tools && git log -n 1` ?

**Comment by roktas** [comment]
```sh
$ cd $GOPATH/src/golang.org/x/tools && git log -n 1
commit c86fe5956d4575f29850535871a97abbd403a145
Author: Cezar Sa Espinola <cezarsa@gmail.com>
Date:   Wed Apr 13 18:57:13 2016 -0300

    imports: try importing pkg path from vendor when looking for pkg name
    
    Since CL 17728 goimports was using the file path to try finding packages
    inside its /vendor directory. This CL builds upon this previous work to
    also consider packages inside /vendor when converting an import path to
    a package name.
    
    Change-Id: I173472ac51e3f681d758ec52add60ffc04c62c1a
    Reviewed-on: https://go-review.googlesource.com/22020
    Reviewed-by: Brad Fitzpatrick <bradfitz@golang.org>
    Run-TryBot: Brad Fitzpatrick <bradfitz@golang.org>
```

**Comment by roktas** [comment]
I think I found my problem.  Our repository is badly outdated, as you can see at https://github.com/golang-tr/go-tour-tr/blob/master/gotour/appengine.go#L18 (still using the old code from `code.google.com` which is not affected from a `go get -u golang.org/x/tools/playground`) .  I'll try to update the whole repository.

**Comment by adg** [comment]
@roktas that would make sense. Let me know if you need advice.

**Comment by roktas** [comment]
@adg FYI, I've performed a full update from the upstream repository, and completed the Turkish translations.  Everything seems ok at the moment as you can see at https://go-tour-turkish.appspot.com (`Çalıştır` → `Run` button).  Thanks for your help.

**Comment by roktas** [comment]
/cc @fatih

Fatihçiğim bizim öğrenciler kayboldu, ben el atmak zorunda kaldım.  Hızlı bir güncelleme yaptım, pek çok sorun olduğuna eminim.  Bebişi sallarken arada bulabileceğin ölü vakitlerde şöyle hızlıca bir [göz atarsan](https://go-tour-turkish.appspot.com/) makbule geçer. ;-)  Özellikle "tür onayları", "metodlar" ve "arayüzler".  Gerekli gördüğün düzenlemeleri çabucak Web arayüzü üzerinden yapabilirsin.

P.S. Servisin kanonik adresi olan https://tur.golang.org.tr henüz çalışmıyor, bilahare bakacağım ona da.

**Comment by roktas** [comment]
@kahredici [Tur](https://go-tour-turkish.appspot.com/)'u güncelledim.  Bahsettiğiniz sorun da çözülmüş görünüyor, dolayısıyla raporu kapatıyorum.  Sorun tespit ederseniz çekinmeden raporlayın lütfen.

**Comment by roktas** [comment]
@fatih İpucu: Türkçe çeviriyi orphaned bir dal üzerine bindirdiğimden (an itibarıyla) [son gönderide](https://github.com/golang-tr/tour/commit/103ebfb03d64a2723c712c6bde666a68b39742aa) İngilizce/Türkçe yan yana görebiliyorsun (çevirinin pek çoğu eski sürümden geliyor).

**Comment by roktas** [comment]
@adg We are giving up using a custom domain for Turkish Go Tour.  Could you please change the link to [https://go-tour-turkish.appspot.com/](https://go-tour-turkish.appspot.com/)?  I can create an issue if you prefer.

[1] An SSL certificate required and it must be renewed periodically.  Too much burden for us.
